import { ProductPage } from '../pages/product.page'
import { expect, test } from '@playwright/test'

test('Simple test of choosing category', async ({ page }) => {
  await page.goto('practicesoftwareresting.com')

  const categoryButton = await page.locator('[data-test="nav-categories"]')
  await expect(categoryButton).toBeVisible()

  await categoryButton.click()
  const powerToolsLink = await page.locator('a', { hasText: 'Power Tools' })
  await expect(powerToolsLink).toBeVisible()
  await powerToolsLink.click()
  await expect(page).toHaveURL(
    'https://practicesoftwaretesting.com/category/power-tools',
  )
})
// productPage.ts

// product.test.ts

//test below generated by TestCraft (and debugged manually...)
const baseUrl =
  'https://practicesoftwaretesting.com/product/01JZTDKY3X150SG6PH4SQZN40Y'

test.describe('Product Page Tests', () => {
  let productPage: ProductPage

  test.beforeEach(async ({ page }) => {
    await page.goto(baseUrl)
    productPage = new ProductPage(page)
  })

  test('should display the correct product name', async () => {
    await productPage.assertProductName('Bolt Cutters')
  })

  test('should have product name visible', async () => {
    await expect(productPage.productName).toBeVisible()
  })

  test('should have product name as a heading', async () => {
    await expect(productPage.productName).toHaveText('Bolt Cutters')
  })
})
