import { BasePage } from './base.page'
import { Page } from '@playwright/test'

export class ProductPage extends BasePage {
  // Locators

  constructor(page: Page) {
    super(page)

    // Initialize all locators
  }
}
// class generated by TestCraft also modified a little manually
