import { BasePage } from './base.page'
import { Locator, Page } from '@playwright/test'

export class ProductPage extends BasePage {
  readonly productName: Locator

  constructor(page: Page) {
    super(page)
    this.productName = page.locator('[data-test=product-name]')
  }

  //   get productName(): Locator {
  //     return this.page.locator('[data-test=product-name]')
  //   }

  async getProductNameText(): Promise<string> {
    return (await (await this.productName).textContent()) || ''
  }

  async assertProductName(expectedName: string): Promise<void> {
    const actualName = await this.getProductNameText()
    if (actualName !== expectedName) {
      throw new Error(
        `Expected product name to be "${expectedName}", but got "${actualName}"`,
      )
    }
  }
}
// class generated by TestCraft also modified a little manually
